apiVersion: v1
kind: Pod
metadata:
  name: python-flask-app
  labels:
   app: python-flask
   region: IN
   rack: r1
   version: "1.1"
spec:
  containers:
    - name: python-flask-app
      image: paulinomreyes/dockerflask
      ports:
      - containerPort: 8000
